circonus-labs/gosnowth

- README.md
- cmd/example/retrieval.go
- cmd/example/state.go
- cmd/example/submission.go
- cmd/main.go
migration from github.com/circonus/gosnowth to github.com/circonus-labs/gosnowth
> update naming, moving gosnowth repository

- README.md
- client.go
- client_test.go
Previously the NewSnowthClient could return an empty set of snowth
nodes, which did not inform the caller that a largely useless struct was
returned.
Added crude unit test for this specific case. Additional tests should be
added for the client module.
> Return error to the if no snowth nodes activated

- client.go
- config.go
- config_test.go
- examples/retrieval.go
- examples/state.go
- examples/submission.go
- go.mod
- go.sum
- gossip.go
- gossip_test.go
- histogram.go
- histogram_test.go
- location.go
- nnt.go
- raw.go
- raw_test.go
- rollup.go
- state.go
- tags.go
- text.go
- topology.go
- toporing.go
- Is completely backwards compatible with all previous versions of gosnowth. All changes introduced by this PR are non-breaking for any existing code using gosnowth.
- Introduces a Config type which allows creation of SnowthClient values with configurable properties. Values that can be set with configuration are:
- DialTimeout sets a timeout value for the initial connection to an IRONdb server. Its default value is 500 milliseconds.
- Discover sets whether or not the client should attempt to discover other IRONdb nodes using topology data retrieved from its provided servers. Its default value is false.
- Servers sets the addresses of the IRONdb servers that should be used by the client.
- Timeout sets a timeout value for the full duration of requests to IRONdb servers.  Its default value …
> Implement context and config for SnowthClient

- client.go
- client_test.go
- Fixes an issue with the SnowthClient.WatchAndUpdate() feature. It was not resetting the interval timer, resulting in node status polling continuously.  This change fixes the interval timing.
> Fix issue with watch interval timer

- tags.go
- tags_test.go
- Implements support for the "check_tags" field contained in results returned from IRONdb queries using the `/find/<account>/tags` endpoint.
- This field contains information about the checks containing metric results, and additional user defined tag data about those checks.
> Add support for check_tags field used by FindTags()

- client.go
- client_test.go
- gossip_test.go
- histogram_test.go
- location_test.go
- nnt_test.go
- raw_test.go
- rollup_test.go
- stats.go
- stats_test.go
- tags_test.go
- text_test.go
- topology_test.go
- toporing_test.go
- Implements SnowthClient.GetStats() functionality.  This retrieves metrics and stats data about an IRONdb node via the `/stats.json` API endpoint.
- The Stats type is defined to hold the metric data returned, and it stores the data in a `map[string]interface{}`, allowing the metrics exposed by IRONdb to change without breaking gosnowth.  But, helper methods are defined on the type to check and retrieve commonly used information.
- The code that creates and updates SnowthNode values has been changed to pull information via GetStats instead of GetState, so that additional information about the version of IRONdb running on a node can be obtained using the SnowthNode value.
- Adds an assignable middleware function that can run during the SnowthClient.WatchAndUpdate() process.
- This can …
> Implement GetStats functionality

- ChangeLog.md
- client.go
- tags.go
- tags_test.go
- Adds an `activity` field to the FindTagsItem structure to capture this new data returned from the IRONdb API.
- Adds unit tests to verify the data returned from IRONdb deserializes correctly into the FindTagsItem structure.
> CIRC-3247: Add activity field to FindTagsItem data

- ChangeLog.md
- README.md
- caql.go
- caql_test.go
- common.go
- common_test.go
- df4.go
- df4_test.go
- docs/SnowthClients.md
- fetch.go
- fetch_test.go
- histogram.go
- histogram_test.go
- lua.go
- lua_test.go
- rollup.go
- rollup_test.go
- text.go
- text_test.go
- Adds methods for listing Lua extensions and calling any Lua extension via the IRONdb extension APIs.
- Adds specific support for CAQL queries via a separate method.
- Adds support for a Go data structure representation of the DF4 data format.
- Updates unit tests to cover all new methods and types.
- Adds support for reading histogram data, and adds types to represent histogram data responses.
- Improves handling of rollup data responses and adds support for legacy / type=all rollup data responses.
- Adds support for making data requests using the /fetch API.
- Allows rollup values to be read for any type, not only 'average' values.
> CIRC-1572: Implement Lua extension APIs, DF4, CAQL

- ChangeLog.md
- caql.go
- caql_test.go
- client.go
- common.go
- Changed the signature for the SnowthClient.GetCAQLQuery() methods to use the
new CAQLQuery type as a parameter. This allows all available parameters to be
used when executing CAQL queries.
- Added the CAQLError type which may be returned by the
SnowthClient.GetCAQLQuery() methods as an error if the error returned from the
corresponding IRONdb API call can be represented from this type. This allows
retrieval of extended error information when CAQL query requests fail.
- The SnowthClient.GetCAQLQuery() methods now send CAQL query requests to IRONdb
via a POST request. This prevents potential problems with query string encoding.
> CIRC-3360: Improve CAQL queries and errors

- ChangeLog.md
- rollup.go
- Adds a nil check to prevent panicking when unmarshalling rollup JSON data containing null values.
> CIRC-2444: Fix missing nil check in rollup JSON handling

- ChangeLog.md
- client_test.go
- common_test.go
- examples/retrieval.go
- tags.go
- tags_test.go
- Adds a new FindTagsLatest type and a new 'Latest' field to the `FindTagsItem` type to support `SnowthClient.FindTags()` returning the latest data values when requested from the IRONdb find call.
- Changes the signature of the `SnowthClient.FindTags()` and  `SnowthClient.FindTagsContext()` methods to accept a `*FindTagsOptions` argument. This argument contains the values for the supported IRONdb find operation query parameters.
> CIRC-4388: Support new IRONdb find parameters

- caql.go
- client.go
- df4.go
- df4_test.go
- Contains the upstream changes to the work that has been done to this library within the GoAPI project.
- Adds support for the Explain parameter and results for CAQL requests.
- Adds support for tracing and dumping request payload to stdout for diagnostic purposes.
> CIRC-2444: Migrate updates from GoAPI into gosnowth

- ChangeLog.md
- activity.go
- caql.go
- client.go
- client_test.go
- common.go
- config.go
- config_test.go
- fetch.go
- gossip.go
- histogram.go
- location.go
- lua.go
- nnt.go
- raw.go
- rollup.go
- state.go
- stats.go
- tags.go
- tags_test.go
- text.go
- topology.go
-  Adds an option, which is off by default, but can be set with SnowthClient.SetRetries(), that allows the client to retry requests to IRONdb that fail due to network errors on other available nodes, a specified number of times, or until there are no more know nodes to try.
- Changes all functions to only lookup which node to call if a specific node is not provided to the function.
> CIRC-5002: Implement option to retry on network errors

- ChangeLog.md
- caql_test.go
- client.go
- config_test.go
* Adds additional debug logging, if configured, to support better tracking of IRONdb request retries.
* Fixes a bug that would cause failures on POST requests to IRONdb if the request needed to be retried on more than one node.
> CIRC-5002: Fix retry POST request bug and improve debug logs

- ChangeLog.md
- caql.go
- caql_test.go
- df4.go
- fetch.go
- fetch_test.go
- It is possible for DF4 JSON responses from IRONdb to contain data values of `inf` and also possibly `NaN`.
- These values need to be removed prior to passing any data to the Go standard library JSON parser, or parsing will fail.
- These values have to be replaced in the raw []byte data, as the error they induce happens before any custom UnmarshalJSON code is called.
> CIRC-5228: Allow infinity and NaN DF4 data values

- ChangeLog.md
- df4.go
- fetch_test.go
* Fixes a bug affecting how gosnowth handles +inf, -inf, and NaN values if they are contained in the DF4 JSON response from IRONdb for fetch calls. When these values are the last in a set of data, gosnowth will no longer fail with a failed to decode JSON error.
> CIRC-6053: Fix DF4 inf value handling bug

- ChangeLog.md
- tags.go
- tags_test.go
* upd: Added support for `_count_only` requests using the FindTags functions.
> CIRC-6072: Allow gosnowth to handle _count_only FindTags requests

- ChangeLog.md
- tags.go
* fix: Changed the type of the `_count_only` results type.
> CIRC-6072: Fix the type of the _count_only results value

- client.go
- examples/retrieval.go
- examples/submission.go
- raw_test.go
* Corrects some spelling errors.
* Adds an additional flat buffer write benchmark.
* Adds examples for using flat buffer writes, fetch queries, and CAQL queries.
> CIRC-2444: Additional examples and benchmarks

- ChangeLog.md
- client.go
- examples/submission.go
- go.mod
- go.sum
- histogram.go
* upd: Requests to IRONdb will now include a X-Snowth-Timeout header. The value will be 1 second less than the total request timeout configuration value.
> CIRC-6535: Add X-Snowth-Timeout header

- .golangci.yml
- ChangeLog.md
- caql.go
- caql_test.go
- client.go
- df4.go
- df4_test.go
- fetch_test.go
- histogram_test.go
- location_test.go
- nntbs.go
- nntbs_test.go
- rollup_test.go
- tags.go
- tags_test.go
- topology_test.go
* add: Added support for start and end time strings to the tags API.
* fix: Struct alignments, ReplaceAll, and other linter fixes.
> CIRC-7239: Add support for time strings to tags, linter fixes

- ChangeLog.md
- client.go
* upd: Randomizes the IRONdb cluster nodes that will be retried in cases of network connection failure.
> CIRC-8083: Randomize IRONdb nodes to retry on network errors

- ChangeLog.md
- caql_test.go
- client.go
- client_test.go
* upd: NewClient() now requires a context when being called. This allows for context terminations to happen during the process of creating and initializing a new SnowthClient.
> CIRC-8169: Support context termination in NewClient()

- ChangeLog.md
- client.go
- examples/retrieval.go
- examples/state.go
- examples/submission.go
- metric.go
- metric_test.go
* fix: Fixes the metric name parser to correctly use curly brackets when parsing measurement tags.
* fix: Fixes connection retries to always try the specified node first then randomly pick from active cluster nodes for retries.
* fix: Fixes broken examples code.
> CIRC-8303: Fix measurement tag parsing to use curly brackets

- ChangeLog.md
- client.go
* fix: Corrects a bug that was causing gosnowth to retry requests that should not be retried because they failed due to context cancelation or due to a user facing error.
* upd: Improves the gosnowth debug logging for readability and allows the traceID to be used to track requests across multiple retries.
NOTE: I have already applied this as a patch to production so that there would not be a risk of overwhelming any snowth clusters with context cancel or user errors being retried multiple times. If this change is approved, I will make a goapi PR containing this update and then when that is approved I can make an official release.
> CIRC-8570: Do not retry on certain snowth errors, improve logging

- ChangeLog.md
- client.go
* upd: Changes the method used to stop retrying when contexts are canceled or reach timeout. This is to support upcoming changes in go v1.19.
* This is needed because in go v1.19 network cancellation and timeout errors from the net package will return true for errors.Is(err, context.DeadlineExceeded) or errors.Is(err, context.Canceled), and the current check would stop processing connection retries for some of the exact connection errors where we do want to be processing retries even though the context for DoRequestTimeout() has still not terminated. See: https://tip.golang.org/doc/go1.19.
> CIRC-8570: Make context terminated check compatible with go 1.19

- ChangeLog.md
- tags.go
- tags_test.go
* fix: Corrects a bug in how check tag encoding is handled that was preventing UpdateCheckTags() from correctly updating check tags requiring base64 encoding.
> CIRC-3356: Fix issue with check tags base64 encoding

- .golangci.yml
- ChangeLog.md
- caql.go
- df4.go
- df4_test.go
* upd: Changes the DF4 data types to include fields that were missing for `head.error` and `head.warning`. Adds functionality to allow extracting typed data from DF4 data values.
> CIRC-8800: Update DF4 types to include missing fields

- .golangci.yml
- ChangeLog.md
- activity_test.go
- caql.go
- caql_test.go
- client.go
- common_test.go
- df4.go
- df4_test.go
- examples/retrieval.go
- examples/submission.go
- fetch.go
- go.mod
- histogram_test.go
- lua.go
- metric.go
- nnt_test.go
- nntbs.go
- nntbs_test.go
- numeric_test.go
- raw.go
- raw_test.go
- tags_test.go
- text_test.go
- topology.go
- topology_test.go
* upd: Removes all use of the deprecated ioutil package, includes some code cleanup and adds additional linters.
* upd: Disables the deprecated ifshort linter.
* upd: Updates the minumum go build version to 1.17.
* upd: Replaces some number constants with their named constants from the standard library.
> CIRC-8973: Remove ioutil package, update go build version, additional linters

- .golangci.yml
- ChangeLog.md
- client.go
* fix: Ensures that snowth nodes loaded by the topology discovery process are properly populated with all stats information, and are correctly added as inactive servers if they are not responding to network requests.
> CIRC-9720: Make sure nodes are tested active and populated with stats upon discovery

- ChangeLog.md
- tags.go
- tags_test.go
* upd: Changes the mechanism of UpdateCheckTags() to mitigate a race condition that can occur if check tags are being rapidly changed. It will now always attempts to add the full set of check tags being submitted rather than only the ones that snowth thinks do not already exist.
> CIRC-9833: Add all tags every time UpdateCheckTags is called

- ChangeLog.md
- promql.go
* upd: Adds a PromQLError type, which duplicates the PromQL response envelope, but also functions as a Go error type.
> CIRC-9694: Implement PromQLError type for PromQL compatibility support

- ChangeLog.md
- client.go
- common.go
* fix: Corrects a critical bug that could cause snowth client creation to fail if a single cluster node does not respond within the context timeout.
* upd: Removes the Config.Discover option and the deprecated NewSnowthClient() function. These were not used and were previously replaced by NewClient() and the WatchAndUpdate() functionality.
> CIRC-9872: Address issue causing client creation failure for single failing node

- ChangeLog.md
- client.go
* add: Adds a configuration item, DenyHosts, to allow a list of hosts to always be considered inactive, regardless of topology discovery.
> CIRC-9964: Implement deny hosts configuration item

- ChangeLog.md
- metric.go
- metric_test.go
* fix: Removes quote handling from the metric name parser. This handling is correct for tag queries, but not for canonical name parsing.
> CIRC-9980: Remove quote handling from metric name parser

- ChangeLog.md
- metric.go
- metric_test.go
* fix: Restores some quote handling for metric name parsing but corrects the bug that was causing removal of quotes from quoted values.
> CIRC-9980: Restore some quote processing to metric stream tags

- ChangeLog.md
- promql.go
- promql_test.go
* upd: Adds support for fractional seconds for PromQL queries for compatibility. PromQL fractional seconds are truncated when converting to CAQL queries.
> CIRC-9934: Add support for PromQL fractional time seconds

- ChangeLog.md
- promql.go
- promql_test.go
* add: Adds PromQL support for series queries via PromQLSeriesQuery().
* add: Adds PromQL support for label names queries via PromQLLabelQuery().
* add: Adds PromQL support for label values queries via PromQLLabelValuesQuery().
* add: Adds conversion of PromQL series selectors into IRONdb tag queries via ConvertSeriesSelector().
> CIRC-9935, CIRC-9936: Implement support for PromQL series & label queries

- ChangeLog.md
- promql.go
- promql_test.go
* fix: Ensures PromQLMetadataQuery() only returns metrics with valid PromQL types and that can be expressed as PromQL types.
> CIRC-10033: Ensure PromQLMetadataQuery() returns valid PromQL types

- ChangeLog.md
- tags.go
- tags_test.go
* refactor!: Modifies the FindTagsResult values returned by the FindTags() functions so that they do not include a separate FindCount value, but use the count and estimate fields on the FindTagsResult when the query is count only.
* feat: Includes accurate values in FindTagsResult.Estimate when results from a FindTags() query return estimated results from IRONdb. This can be used to determine that a timeout occurred during processing by IRONdb.
> refactor!: CIRC-10299: Update FindTags() to return whether the results are an estimate
